sudo: required

services:
    - docker

before_install:
    - docker build -t srinivask61/loginapp .

script:
    - docker run srinivask61/loginapp npm test

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push srinivask61/loginapp

deploy:
    provider: elasticbeanstalk
    region: us-west-2
    app: docker-loginapp
    env: Dockerloginapp-env
    bucket_name: elasticbeanstalk-us-west-2-533316587000
    bucket_path: docker-loginapp
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY
